@include('templates.header')
@include('templates.nav')
@include('templates.login-modal')
@include('templates.centerer')
@include('templates.main-start')
@include('templates.welcome')
@include('templates.profile-template', ['what' => 'templates.profile-activity-template'])
@include('templates.footer')