@include('templates.header')
@include('templates.nav')
@include('templates.login-modal')
@include('templates.centerer')
@include('templates.main-start')
@include('templates.welcome')
@include('templates.register-template')
@include('templates.footer')